/*
 * ============================================================================
 * Program 12 : Exception Propagation
 * ============================================================================
 *
 * Program Statement:
 * Write a Java program to demonstrate how an exception propagates through
 * multiple method calls until it finds a matching exception handler.
 *
 * Objective:
 * - Understand Exception Propagation.
 * - Learn how an exception moves up the call stack.
 * - Observe how a caller can handle an exception generated by another method.
 *
 * Concepts Covered:
 * - Exception Propagation
 * - Call Stack
 * - ArithmeticException
 * - Method Calls
 * - Stack Unwinding
 * ============================================================================
 */

public class ExceptionPropagation {

    public static void methodThree() {

        System.out.println("Inside methodThree()");

        int result = 10 / 0;

        System.out.println("Result : " + result);

    }

    public static void methodTwo() {

        System.out.println("Inside methodTwo()");

        methodThree();

        System.out.println("Leaving methodTwo()");

    }

    public static void methodOne() {

        System.out.println("Inside methodOne()");

        methodTwo();

        System.out.println("Leaving methodOne()");

    }

    public static void main(String[] args) {

        System.out.println("Program Started");

        try {

            methodOne();

        }

        catch (ArithmeticException e) {

            System.out.println("Exception Caught in main() : " + e.getMessage());

        }

        System.out.println("Program Finished");

    }

}

/*
 * ============================================================================
 * Sample Output:
 * ============================================================================
 *
 * Program Started
 * Inside methodOne()
 * Inside methodTwo()
 * Inside methodThree()
 * Exception Caught in main() : / by zero
 * Program Finished
 * ============================================================================
 */

/*
 * ============================================================================
 * Explanation:
 * ============================================================================
 *
 * 1. main() calls methodOne().
 * 2. methodOne() calls methodTwo().
 * 3. methodTwo() calls methodThree().
 * 4. Inside methodThree(), the expression 10 / 0 throws an
 *    ArithmeticException.
 * 5. methodThree() does not contain a matching catch block.
 * 6. The exception propagates back to methodTwo().
 * 7. methodTwo() also does not handle the exception.
 * 8. The exception propagates back to methodOne().
 * 9. methodOne() also does not handle the exception.
 * 10. The exception finally reaches main().
 * 11. main() contains a matching catch block and handles the exception.
 * 12. Execution then continues after the try-catch block.
 *
 * Notice that:
 *
 *     "Leaving methodTwo()"
 *     "Leaving methodOne()"
 *
 * are never printed because those method executions are interrupted while
 * the exception propagates up the call stack.
 * ============================================================================
 */

/*
 * ============================================================================
 * Call Stack Before Exception:
 * ============================================================================
 *
 * main()
 *   |
 *   +-- methodOne()
 *         |
 *         +-- methodTwo()
 *               |
 *               +-- methodThree()
 *                     |
 *                     +-- ArithmeticException
 *
 *
 * Exception Propagation:
 *
 * methodThree()
 *      |
 *      | Not Handled
 *      v
 * methodTwo()
 *      |
 *      | Not Handled
 *      v
 * methodOne()
 *      |
 *      | Not Handled
 *      v
 * main()
 *      |
 *      | Matching catch Found
 *      v
 * Exception Handled
 *
 * This removal of method frames while searching for an exception handler is
 * commonly referred to as stack unwinding.
 * ============================================================================
 */

/*
 * ============================================================================
 * Key Points:
 * ============================================================================
 *
 * ✓ An exception can propagate from one method to its caller.
 * ✓ Propagation continues until a matching handler is found.
 * ✓ If no method handles the exception, it eventually reaches the JVM.
 * ✓ An unhandled exception reaching the JVM terminates the program.
 * ✓ Statements remaining in methods being unwound are not executed.
 * ✓ The JVM searches through the call stack for an appropriate handler.
 * ✓ Runtime exceptions propagate automatically without requiring throws.
 * ============================================================================
 */
