

class Demo{

	public static void main(String[] args){
	
		int x = 10;
		int y = 20;

		System.out.println("In main method");
		System.out.println(x+y);
	}
}



/* Output :
 * 	In main method
	30
 *
 *
 * Explanation:
 * 	When the above java program is compiled using javac version 1.8 and executed using java version 11, the concept of backward
 * 	compatibility come into the picture. Java maintains strong backward compatibility, which means progra, compiled using an older
 * 	java compiler can run on a newer Java Runtime Environment.
 *
 * 	Here, first the source file Demo.java is compiled using the command javac Demo.java with JDK 1.8. Suring compilation, the Java 
 * 	compiler checks the syntax of the program and converts the source code into bytecode. After successful compilation, a .class file
 * 	gets created. This .class file contains Java bytecode compatible with 1.8 specification.
 *
 * 	When we run the program using Java 11 with the command java Demo, the java 11 JVM starts the execution process. At this stage, the
 * 	Class Loader Subsystem loads the Demo.class file into the JVM memory. Since Java is designed to be backward compatible, the Java 11
 * 	JVM can execute bytecode generated by older compilers such as Java 8 without any modification.
 *
 * 	0xCAFEBABE
 *
 * 	This is called the magic number. It acts like a fingerprint that identifies the file as a vaid Java class file. When the JVM's
 * 	class loader reads a .class file, the first thing it checks is this number. If the value is not 0xCAFEBABE, the JVM immidiately
 * 	rejects the file because it knows the file is not a proper Java bytecode file.
 *
 * */
