

/*
------------------------------------------------------------
Program 04 : Autoboxing

Language    : Java
Difficulty  : ⭐⭐ Beginner

Concepts Covered

	✔ Autoboxing
	✔ Primitive to Wrapper Conversion
	✔ Compiler Conversion
	✔ valueOf()

Expected Time : 20 Minutes
------------------------------------------------------------

Problem Statement

	Write a Java program to demonstrate Autoboxing by
	assigning primitive values to their corresponding
	Wrapper Classes.

	Print all Wrapper objects to verify that the primitive
	values are automatically converted into objects.

------------------------------------------------------------
*/

public class AutoboxingDemo {

    public static void main(String[] args) {

        int employeeAge = 25;
        double productPrice = 1999.99;
        char grade = 'A';
        boolean isPaymentSuccessful = true;
        long mobileNumber = 9876543210L;

        Integer employeeAgeObject = employeeAge;
        Double productPriceObject = productPrice;
        Character gradeObject = grade;
        Boolean paymentStatusObject = isPaymentSuccessful;
        Long mobileNumberObject = mobileNumber;

        System.out.println("Employee Age      : " + employeeAgeObject);
        System.out.println("Product Price     : " + productPriceObject);
        System.out.println("Grade             : " + gradeObject);
        System.out.println("Payment Status    : " + paymentStatusObject);
        System.out.println("Mobile Number     : " + mobileNumberObject);

    }

}

/*
------------------------------------------------------------
Output

	Employee Age      : 25
	Product Price     : 1999.99
	Grade             : A
	Payment Status    : true
	Mobile Number     : 9876543210

------------------------------------------------------------
Explanation

	Autoboxing is the automatic conversion of a primitive
	data type into its corresponding Wrapper Class object.

	When the compiler encounters

	Integer employeeAgeObject = employeeAge;

	it internally converts it into

	Integer employeeAgeObject = Integer.valueOf(employeeAge);

	Similarly,

	Double productPriceObject = productPrice;

	becomes

	Double productPriceObject = Double.valueOf(productPrice);

	The conversion is performed automatically by the Java
	compiler, making the code shorter and easier to read.

------------------------------------------------------------
Important Points

	✔ Autoboxing was introduced in Java 5.

	✔ Autoboxing converts primitive values into Wrapper
	objects.

	✔ The conversion is performed automatically by the
	compiler.

	✔ Autoboxing internally uses valueOf().

	✔ Autoboxing improves code readability.

------------------------------------------------------------
Common Mistakes

❌ Assuming Autoboxing uses deprecated constructors.

Autoboxing internally uses

valueOf()

and not

new Integer().

------------------------------------------------------------

❌ Thinking Autoboxing creates primitive values.

Autoboxing always creates Wrapper objects.

------------------------------------------------------------

❌ Performing excessive Autoboxing inside performance-
critical loops.

Repeated Boxing and Unboxing may introduce unnecessary
overhead.

------------------------------------------------------------
Follow-up Interview Questions

1.

What is Autoboxing?

------------------------------------------------------------

2.

Who performs Autoboxing?

------------------------------------------------------------

3.

Which method does Autoboxing use internally?

------------------------------------------------------------

4.

In which Java version was Autoboxing introduced?

------------------------------------------------------------

5.

What are the advantages of Autoboxing?

------------------------------------------------------------
Real World Use Cases

	✔ Collections Framework

	✔ Generics

	✔ Streams API

	✔ Method Parameters

	✔ Method Return Values

	✔ Enterprise Java Applications

------------------------------------------------------------
Practice Questions

1.

Create Wrapper objects using Autoboxing for all eight
primitive data types.

------------------------------------------------------------

2.

Replace Autoboxing with explicit

valueOf()

calls and compare the code.

------------------------------------------------------------

3.

Use Autoboxing while adding elements into an

ArrayList<Integer>.

------------------------------------------------------------

4.

Observe the compiler-generated bytecode using

javap

and identify the

valueOf()

method call.

------------------------------------------------------------
*/
